#amazon aws
AWS_ACCESS_KEY_ID: AKIAJBX6PMC2FLCJYP2Q
AWS_SECRET_ACCESS_KEY: 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
development:
  SENDGRID_USERNAME: app18559451@heroku.com
  SENDGRID_PASSWORD: arydhzit
  AWS_BUCKET: hale-bloccit-development
  FACEBOOK_ID: 1425678790994115
  FACEBOOK_SECRET: 6ff70c1f969230a1eb6db3c483c88091
production:
  AWS_BUCKET: hale-bloccit-production
  FACEBOOK_ID: 226410877527485
  FACEBOOK_SECRET: d7d33c8781e42cc22092bbf35243e41d 